DROP TABLE if EXISTS wastes_types;

CREATE TABLE associations (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
points INTEGER NOT NULL,
image VARCHAR(255) NOT NULL
);

CREATE TABLE waste_types (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
value VARCHAR(255) NOT NULL,
label VARCHAR(255) NOT NULL,
className VARCHAR(255) NOT NULL
);


